<?php

########################################################################
# Extension Manager/Repository config file for ext: "itmedia2"
#
# Auto generated by Extension Builder 2013-03-27
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
    'title' => 'IT and Media Directory',
    'description' => 'With this extension you can build your own industry directory for IT and Media',
    'category' => 'plugin',
    'author' => 'Markus Kugler',
    'author_email' => 'projects@jweiland.net',
    'author_company' => 'jweiland.net',
    'shy' => '',
    'priority' => '',
    'module' => '',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '1',
    'createDirs' => '',
    'modify_tables' => '',
    'clearCacheOnLoad' => 0,
    'lockType' => '',
    'version' => '0.1.1',
    'constraints' => array(
        'depends' => array(
            'typo3' => '6.2.14-7.6.99',
            'maps2' => '2.5.1-2.99.99',
            'yellowpages2' => '1.0.0-1.0.999',
        ),
        'conflicts' => array(
        ),
        'suggests' => array(
        ),
    ),
);
