services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  JWeiland\Itmedia2\:
    resource: '../Classes/*'

  JWeiland\Itmedia2\Configuration\ExtConf:
    public: true

  JWeiland\Itmedia2\EventListener\AddPaginatorEventListener:
    tags:
    - name: event.listener
      event: JWeiland\Itmedia2\Event\PostProcessFluidVariablesEvent

  JWeiland\Itmedia2\EventListener\AddGlossaryEventListener:
    tags:
    - name: event.listener
      event: JWeiland\Itmedia2\Event\PostProcessFluidVariablesEvent
      after: JWeiland\Itmedia2\EventListener\AddPaginatorEventListener
